# Generated by Django 4.2.17 on 2026-05-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("course", "0003_course_summary_es_course_summary_fr_course_title_es_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoWatchProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_seconds",
                    models.FloatField(
                        default=0.0,
                        help_text="Last watched playback time in seconds (HTML5 video currentTime).",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        default=0.0,
                        help_text="Video duration when last reported (for percentage).",
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Cached 0–100 for list views and dashboards.",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="True when the viewer reached ~95% or the 'ended' event.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_watch_progress",
                        to="accounts.student",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_progress",
                        to="course.uploadvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video watch progress",
                "verbose_name_plural": "Video watch progress",
                "indexes": [
                    models.Index(
                        fields=["student", "video"],
                        name="course_vide_student_f1c312_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="videowatchprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "video"), name="uniq_student_video_watch_progress"
            ),
        ),
    ]
